# theme to import
theme: jekyll-theme-chirpy

# site language › http://www.lingoes.net/en/translator/langcode.htm
# if the same name as a file in `_data/locales` the layout language is also changed,
# otherwise layout language uses default 'en'.
lang: en

# timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: America/New_York

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------
title: Optimization Impostor's Compendium  # displayed as page title
tagline: Prescriptive Analytics Lore for the Adventurous.  # displayed as sub-title
description: >-  # used by seo meta and the atom feed
  Prescriptive Analytics Lore for the Adventurous.
url: "https://opt-compendium.com"  # protocol & domain ... NB: doesn't end with '/'
github:
  username: MartinLaskowski
# twitter: 
#   username: @martylasky
social:
  name: Martin Laskowski  # displayed as default author of posts and copyright owner (in footer)
  email: martinlaskowski@me.com
  links:  # first element serves as copyright owner's link
    - https://www.linkedin.com/in/martinlaskowski
    - https://github.com/MartinLaskowski
    - https://www.youtube.com/@MartinLaskowski
    # - https://twitter.com/martylasky
google_site_verification: M3lVLfb29csl8pv7ImTzE1u0ChgT44czNUqorbUdCoc
# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

google_analytics:
  id: 

theme_mode: # [light|dark] ... empty = follow user's system choice and offer toggle button

# CDN endpoint for images
# once assigned, CDN url is added to image paths starting with '/'
# e.g. 'https://cdn.com'
img_cdn:

# avatar image on sidebar, supports local and CORS resources
avatar: /assets/img/espresso.jpg

# whether to show TOC in posts
toc: true

comments:
  active:  # global switch for posts comments, e.g., 'disqus' ... keep fields empty to disable
  disqus:
    shortname:  # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  utterances:  # utterances settings › https://utteranc.es/
    repo:  # <gh-username>/<repo>
    issue_term:  # < url | pathname | title | ...>
  giscus:  # Giscus options › https://giscus.app
    repo:  # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping:  # optional, default to 'pathname'
    input_position: # optional, default to 'bottom'
    lang:  # optional, default to the value of `site.lang`
    reactions_enabled:  # optional, default to the value of `1`

# optional self-hosted static assets › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, empty means 'false'
    # specify Jekyll environment, empty means both dev and prod
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development|production]

pwa:
  enabled: true # the option for PWA feature

paginate: 13

# The base URL of your site
baseurl: ""

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
